/** Patrones de palabras completas aplicados a descripciones normalizadas. */
export type CategoriaGasto = { id: string; titulo: string; descripcion: string; patrones: readonly [string, string]; excluir: string };
const palabras = (p: string) => `(^| )(${p})( |$)`;
const mantenimiento = palabras('mantenimientos?|reparacion(es)?|repuestos?|overhaul|implementacion(es)?|equipamientos?|instalacion(es)?|accesorios?|acondicionamientos?|reacondicionamientos?|repotenciacion(es)?|mejoras?|seguros?|polizas?|soat|revision(es)? tecnicas?|inspeccion(es)? tecnicas?|lubricacion(es)?|lubricantes?|aceites?|neumaticos?|llantas?|baterias?');
const vaso = palabras('vaso(s)? de leche|pvl');
export const categoriasGasto: readonly CategoriaGasto[] = [
  { id: 'alquiler-camionetas', titulo: 'Alquiler de camionetas', descripcion: 'Alquiler, arrendamiento y renta de camionetas o pick-up.', patrones: [palabras('alquiler(es)?|arrendamientos?|renta(s)?'), palabras('camionetas?|pick ?ups?')], excluir: '$^' },
  { id: 'maquinaria-pesada', titulo: 'Mantenimiento, mejoras y seguros de maquinaria pesada', descripcion: 'Mantenimiento, reparaciones, repuestos, implementaciones, equipamiento, mejoras, seguros, pólizas, SOAT, revisiones técnicas, lubricantes, llantas y baterías, cuando se menciona maquinaria pesada o sus tipos.', patrones: [mantenimiento, palabras('maquinarias? pesadas?|excavadoras?|retroexcavadoras?|motoniveladoras?|cargador(es)? frontal(es)?|tractores?|bulldozers?|volquetes?|rodillos?')], excluir: '$^' },
  { id: 'consultorias', titulo: 'Consultorías', descripcion: 'Servicios descritos como consultoría o asesoría, incluidos los vinculados a expedientes técnicos.', patrones: [palabras('consultorias?|consultor(es)?|asesorias?'), '.*'], excluir: '$^' },
  { id: 'expedientes-tecnicos', titulo: 'Expedientes técnicos', descripcion: 'Elaboración, actualización, revisión y otros conceptos que mencionan expedientes técnicos.', patrones: [palabras('expedientes? tecnicos?'), '.*'], excluir: '$^' },
  { id: 'beneficios-personal', titulo: 'Sindicatos y beneficios del personal', descripcion: 'Sindicatos, canastas y leche expresamente vinculados al personal, trabajadores o convenios colectivos.', patrones: [palabras('sindicatos?|sindical(es)?|sindicalizados?|sindicalizadas?|sitramun|canastas?|leche'), palabras('sindicatos?|sindical(es)?|sindicalizados?|sindicalizadas?|sitramun|personal|trabajador(es)?|trabajadoras?|servidor(es)?|servidoras?|empleados?|empleadas?|obreros?|obreras?|convenios? colectivos?')], excluir: vaso },
  { id: 'vaso-de-leche', titulo: 'Programa Vaso de Leche', descripcion: 'Órdenes que mencionan Vaso de Leche o PVL; no se atribuye toda compra de leche al programa.', patrones: [vaso, '.*'], excluir: '$^' },
  { id: 'mantenimiento-vehiculos', titulo: 'Mantenimiento, mejoras y seguros de camionetas y motos', descripcion: 'Mantenimiento, reparaciones, repuestos, implementaciones, equipamiento, mejoras, seguros, pólizas, SOAT, revisiones técnicas, lubricantes, llantas y baterías vinculados expresamente a camionetas, pick-up, motos o motocicletas.', patrones: [mantenimiento, palabras('camionetas?|pick ?ups?|motos?|motocicletas?|motociclos?|motocars?|motocarros?')], excluir: '$^' },
  { id: 'utiles-oficina', titulo: 'Útiles de oficina y economato', descripcion: 'Útiles y materiales de oficina, economato, talonarios, impresiones, fotocopias, papel bond, tóner, archivadores y similares.', patrones: [palabras('util(es)? (de |para )?(oficina|escritorio)|material(es)? (de |para )?(oficina|escritorio)|suministros? (de |para )?(oficina|escritorio)|economato|talonarios?|impresion(es)?|impresiones|fotocopias?|fotocopiado|papeleria|papel bond|hojas? (a4|a3|bond)|tintas? (para |de )?impresoras?|toner|toneres|cartuchos? de tinta|archivador(es)?|lapiceros?|boligrafos?|grapadoras?|engrapadoras?|grapas?|clips?|folders?|carpetas? de oficina|formatos? impresos?|sellos? de oficina|sellos? automaticos?'), '.*'], excluir: palabras('util(es)? escolares?|material(es)? escolares?') },
  { id: 'vacaciones-navidad', titulo: 'Vacaciones útiles y Navidad', descripcion: 'Actividades de vacaciones útiles y órdenes que mencionan Navidad, conceptos navideños, chocolatadas o panetones.', patrones: [palabras('vacaciones utiles|navidad|navidenos?|navidenas?|chocolatadas?|panetones?|panetons?'), '.*'], excluir: '$^' },
  { id: 'apoyo-social', titulo: 'Apoyo social y coyuntural', descripcion: 'Apoyo social, apoyo coyuntural, asistencia social, ayuda humanitaria y apoyo a damnificados; no incluye cualquier uso genérico de «apoyo».', patrones: [palabras('apoyos? social(es)?|apoyos? coyuntural(es)?|asistencia social|ayudas? social(es)?|ayudas? humanitarias?|donaciones? social(es)?|subvencion(es)? social(es)?|apoyos? (a |para )?(los |las )?damnificados?'), '.*'], excluir: '$^' },
  { id: 'aniversario', titulo: 'Aniversario y celebraciones', descripcion: 'Órdenes que mencionan aniversario, fiestas patronales o celebraciones del distrito; incluye aniversarios de otras instituciones cuando la descripción no distingue al beneficiario.', patrones: [palabras('aniversarios?|fiestas? patronales?|celebracion(es)? (del |de )?(distrito|municipio)|festividades? (del |de )?(distrito|municipio)'), '.*'], excluir: '$^' },
  { id: 'reinado', titulo: 'Reinado y certámenes de belleza', descripcion: 'Órdenes que mencionan reinado, elección o coronación de reinas, Miss, señoritas o certámenes de belleza.', patrones: [palabras('reinados?|reinas?|coronacion(es)?|certamen(es)? de belleza|concursos? de belleza|miss|eleccion(es)? de senoritas?'), '.*'], excluir: '$^' },
  { id: 'prensa', titulo: 'Gastos en prensa', descripcion: 'Prensa, servicios periodísticos, publicidad, difusión, spots, comunicación social y espacios radiales o televisivos identificados en la descripción; no atribuye automáticamente todas las órdenes de una persona a prensa.', patrones: [palabras('prensa|periodistas?|periodisticos?|periodisticas?|publicidad|publicitarios?|publicitarias?|difusion|radiodifusion|spots?|comunicacion social|medios? de comunicacion|relaciones publicas|avisos? (radiales?|televisivos?|publicitarios?)|espacios? (radiales?|televisivos?)|transmision(es)? (radiales?|televisivas?)|servicios? (radiales?|televisivos?)'), '.*'], excluir: palabras('prensas? (hidraulicas?|mecanicas?|industriales?)') },
  { id: 'equipos-computo', titulo: 'Tóner y equipos de cómputo', descripcion: 'Tóner, tintas y cartuchos de impresora; computadoras, laptops, tablets, impresoras, escáneres, monitores, periféricos, componentes y equipos de redes informáticas. Incluye sus servicios cuando el equipo se menciona.', patrones: [palabras('toner|toneres|toners|tintas? (para |de )?impresoras?|cartuchos? (de tinta|de toner|para impresoras?)|equipos? (de )?(computo|informaticos?)|computadoras?|ordenador(es)?|pc(s)?|laptops?|notebooks?|tablets?|ipad(s)?|impresoras?|multifuncionales?|escaner(es)?|scanner(s)?|monitor(es)?|teclados?|mouse(s)?|raton(es)?|discos? (duros?|ssd)|memorias? (ram|usb)|servidor(es)? (informaticos?|de datos)|routers?|switch(es)?|redes? (informaticas?|de datos)|ups|hardware'), '.*'], excluir: palabras('monitor(es)? (de |para )?(vacaciones|talleres|deportes|actividades)|monitor(es)? ambientales?|redes? (de )?pesca') },
  { id: 'seguridad-serenazgo', titulo: 'Seguridad ciudadana y serenazgo', descripcion: 'Serenazgo, seguridad ciudadana, vigilancia, patrullaje, cámaras, alarmas, radios, uniformes e implementos vinculados a seguridad pública municipal.', patrones: [palabras('serenazgo|serenos?|seguridad ciudadana|patrullaje|vigilancia|videovigilancia|camaras? de seguridad|alarmas?|radios? (portatiles?|comunicacion)|chalecos?|uniformes?|botas?|varas?|linternas?|implementos? de seguridad'), '.*'], excluir: palabras('seguridad (industrial|ocupacional|salud)|vigilancia sanitaria|camaras? fotograficas?|personal administrativo|administrativos?|administrativas?') },
  { id: 'limpieza-residuos', titulo: 'Limpieza pública y residuos sólidos', descripcion: 'Recojo de basura, limpieza pública, barrido de calles, residuos sólidos, contenedores, compactadoras, relleno sanitario y herramientas vinculadas al servicio de limpieza.', patrones: [palabras('limpieza publica|limpieza de calles|barrido|recojo (de )?(basura|residuos)|residuos solidos|basura|compactadoras?|camiones? compactadores?|contenedores? (de )?(basura|residuos)|tachos? (de )?(basura|residuos)|papeleras?|relleno sanitario|botadero|escobas?|recogedores?|rastrillos?|bolsas? (negras?|de basura)|servicio de limpieza'), '.*'], excluir: palabras('limpieza (de )?(oficinas?|local(es)?|equipos?|computadoras?|maquinaria)|residuos hospitalarios?|residuos peligrosos?') },
  { id: 'combustible', titulo: 'Gastos en combustible', descripcion: 'Órdenes que mencionan combustible, gasolina, gasohol, diésel, petróleo o biodiésel. Se compara el monto completo de cada orden; los libros no permiten separar productos de una orden mixta.', patrones: [palabras('combustibles?|gasolinas?|gasohol(es)?|diesel|petroleo|biodiesel|db5|d b5|b5 s50'), '.*'], excluir: palabras('combustibles? (nuclear(es)?|solidos?)') },
];
export function categoriaGastoPorId(id: string) { return categoriasGasto.find(c => c.id === id); }
export function coincideCategoriaGasto(categoria: CategoriaGasto, descripcion: string | null): boolean {
  const normal = (descripcion ?? '').normalize('NFD').replace(/\p{M}/gu, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  return categoria.patrones.every(p => new RegExp(p).test(normal)) && !new RegExp(categoria.excluir).test(normal);
}
